env:
    AWS_DEPLOYMENT_ROLE_NAME: CodeCatalystActionCICD
    AWS_REGION: eu-central-1
    SONARCLOUD_TOKEN: VAULT[development/kv/data/sonarcloud data.token]
    PYTHON_KEYRING_BACKEND: keyring.backends.fail.Keyring
    MYPY_CACHE_DIR: ~/mypy_cache
    NPM_CONFIG_//repox.jfrog.io/artifactory/api/npm/:_authToken: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
    NPM_CONFIG_registry: https://repox.jfrog.io/artifactory/api/npm/npm

eks_container: &BUILD_TEMPLATE
    dockerfile: .cirrus/Dockerfile-build
    builder_role: cirrus-builder
    builder_image: docker-builder-v*
    builder_instance_type: t2.medium
    cluster_name: ${CIRRUS_CLUSTER_NAME}
    region: eu-central-1
    namespace: default
    cpu: 2
    memory: 8Gb
    docker_arguments:
        CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}

node_modules_cache_template: &NODE_MODULES_CACHE_TEMPLATE
    node_modules_cache:
        folders:
            - "node_modules"
        fingerprint_script: cat package-lock.json

coverage_cache_template: &COVERAGE_CACHE_TEMPLATE
    coverage_cache:
        folders:
            - "coverage"
        fingerprint_script: echo $CIRRUS_BUILD_ID

install_dependencies_task:
    <<: *NODE_MODULES_CACHE_TEMPLATE
    timeout_in: 30m
    eks_container:
        <<: *BUILD_TEMPLATE
    script:
        make install

run_tests_task:
    <<: *NODE_MODULES_CACHE_TEMPLATE
    <<: *COVERAGE_CACHE_TEMPLATE
    eks_container:
        <<: *BUILD_TEMPLATE
    depends_on:
        - install_dependencies
    script:
        make run-tests

validate_format_task:
    <<: *NODE_MODULES_CACHE_TEMPLATE
    eks_container:
        <<: *BUILD_TEMPLATE
    depends_on:
        - run_tests
        - install_dependencies
    script:
        make validate-format

generate_build_number_task:
    only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_PR_LABELS =~ '.*deploy-dev.*' || $CIRRUS_PR_LABELS =~ ".*deploy-squad.*" || $CIRRUS_PR_LABELS =~ ".*deploy-pr.*"
    eks_container:
        <<: *BUILD_TEMPLATE
    script:
        - source cirrus-env BUILD # to set the environment variable BUILD_NUMBER

sonar_scan_task:
    <<: *COVERAGE_CACHE_TEMPLATE
    eks_container:
        <<: *BUILD_TEMPLATE
    depends_on:
        - run_tests
    script:
        - source .cirrus/scan.sh
