SchemaVersion: '1.0'
Name: 'SonarCloud Scan'
Version: '1.0.0'
Description: 'Scan your projects with SonarCloud, and help developers produce Clean Code'
Configuration:
  SonarProjectBaseDir:
    Description: 'The directory in which the analysis will run'
    Required: false
    Default: '.'
    DisplayName: 'Sonar Project Base Directory'
    Type: string
  SonarProjectKey:
    Description: 'The unique key of your Project in SonarCloud'
    Required: false
    DisplayName: 'Project Key'
    Type: string
  SonarOrganization:
    Description: 'The key of the SonarCloud organization to which the project belongs'
    Required: false
    DisplayName: 'Organization'
    Type: string
  SonarAdditionalArgs:
    Description: 'Any extra arguments to pass to the scanner'
    Required: false
    DisplayName: 'Additional arguments'
    Type: string
  SonarToken:
    Description: 'Token used by the scanner to authenticate to SonarCloud'
    Required: true
    DisplayName: 'Sonar Token'
    Type: string
  SonarBranchName:
    Description: 'Name of the branch to which the analysis applies'
    Required: false
    DisplayName: 'Branch Name'
    Type: string
Inputs:
  Sources:
    Required: true
Environment:
  Required: false
Runs:
  Using: 'node16'
  Main: 'dist/index.js'
